version: '3'
services:
  nginx:
    image: nginx:1.15
    ports:
    - "80:80"
    volumes:
    - ./conf:/etc/nginx
    restart: always
    container_name: nginx
    networks:
      - nginx
  paygo_micro_users:
    image:
networks:
  nginx: